#!/usr/bin/env Rscript

stopifnot(basename(getwd()) == "R9000")

skip <- c("$<-", "[[<-", "$", "[[",
            # "format",
            # "Math", "Ops"
            "print")

txt <- unique(.S3_methods_table[,1]) |>
  setdiff(skip) |>
  purrr::map_chr( ~ glue::glue(
"
#' @export
`{.x}.R7` <- dottr_s3_dispatcher('{.x}')
"))

txt <- c(
"## DO NOT EDIT,
## autogenerated S3 methods by script
## tools/make-dottr-s3-dispatchers.R
", txt)

txt <- paste(txt, collapse = "\n\n")

writeLines(txt, "R/zzz-dottr-s3-dispatchers.R")
