## DO NOT EDIT,
## autogenerated S3 methods by script
## tools/make-dottr-s3-dispatchers.R


#' @export
`!.R7` <- dottr_s3_dispatcher('!')

#' @export
`&.R7` <- dottr_s3_dispatcher('&')

#' @export
`*.R7` <- dottr_s3_dispatcher('*')

#' @export
`+.R7` <- dottr_s3_dispatcher('+')

#' @export
`-.R7` <- dottr_s3_dispatcher('-')

#' @export
`/.R7` <- dottr_s3_dispatcher('/')

#' @export
`[.R7` <- dottr_s3_dispatcher('[')

#' @export
`[<-.R7` <- dottr_s3_dispatcher('[<-')

#' @export
`|.R7` <- dottr_s3_dispatcher('|')

#' @export
`Math.R7` <- dottr_s3_dispatcher('Math')

#' @export
`Ops.R7` <- dottr_s3_dispatcher('Ops')

#' @export
`Summary.R7` <- dottr_s3_dispatcher('Summary')

#' @export
`all.equal.R7` <- dottr_s3_dispatcher('all.equal')

#' @export
`anyDuplicated.R7` <- dottr_s3_dispatcher('anyDuplicated')

#' @export
`anyNA.R7` <- dottr_s3_dispatcher('anyNA')

#' @export
`aperm.R7` <- dottr_s3_dispatcher('aperm')

#' @export
`as.Date.R7` <- dottr_s3_dispatcher('as.Date')

#' @export
`as.POSIXct.R7` <- dottr_s3_dispatcher('as.POSIXct')

#' @export
`as.POSIXlt.R7` <- dottr_s3_dispatcher('as.POSIXlt')

#' @export
`as.array.R7` <- dottr_s3_dispatcher('as.array')

#' @export
`as.character.R7` <- dottr_s3_dispatcher('as.character')

#' @export
`as.data.frame.R7` <- dottr_s3_dispatcher('as.data.frame')

#' @export
`as.double.R7` <- dottr_s3_dispatcher('as.double')

#' @export
`as.expression.R7` <- dottr_s3_dispatcher('as.expression')

#' @export
`as.function.R7` <- dottr_s3_dispatcher('as.function')

#' @export
`as.list.R7` <- dottr_s3_dispatcher('as.list')

#' @export
`as.logical.R7` <- dottr_s3_dispatcher('as.logical')

#' @export
`as.matrix.R7` <- dottr_s3_dispatcher('as.matrix')

#' @export
`as.null.R7` <- dottr_s3_dispatcher('as.null')

#' @export
`as.single.R7` <- dottr_s3_dispatcher('as.single')

#' @export
`as.table.R7` <- dottr_s3_dispatcher('as.table')

#' @export
`as.vector.R7` <- dottr_s3_dispatcher('as.vector')

#' @export
`by.R7` <- dottr_s3_dispatcher('by')

#' @export
`c.R7` <- dottr_s3_dispatcher('c')

#' @export
`cbind.R7` <- dottr_s3_dispatcher('cbind')

#' @export
`chol.R7` <- dottr_s3_dispatcher('chol')

#' @export
`close.R7` <- dottr_s3_dispatcher('close')

#' @export
`conditionCall.R7` <- dottr_s3_dispatcher('conditionCall')

#' @export
`conditionMessage.R7` <- dottr_s3_dispatcher('conditionMessage')

#' @export
`cut.R7` <- dottr_s3_dispatcher('cut')

#' @export
`determinant.R7` <- dottr_s3_dispatcher('determinant')

#' @export
`diff.R7` <- dottr_s3_dispatcher('diff')

#' @export
`dim.R7` <- dottr_s3_dispatcher('dim')

#' @export
`dimnames.R7` <- dottr_s3_dispatcher('dimnames')

#' @export
`dimnames<-.R7` <- dottr_s3_dispatcher('dimnames<-')

#' @export
`droplevels.R7` <- dottr_s3_dispatcher('droplevels')

#' @export
`duplicated.R7` <- dottr_s3_dispatcher('duplicated')

#' @export
`flush.R7` <- dottr_s3_dispatcher('flush')

#' @export
`format.R7` <- dottr_s3_dispatcher('format')

#' @export
`getDLLRegisteredRoutines.R7` <- dottr_s3_dispatcher('getDLLRegisteredRoutines')

#' @export
`is.na.R7` <- dottr_s3_dispatcher('is.na')

#' @export
`is.na<-.R7` <- dottr_s3_dispatcher('is.na<-')

#' @export
`is.numeric.R7` <- dottr_s3_dispatcher('is.numeric')

#' @export
`isSymmetric.R7` <- dottr_s3_dispatcher('isSymmetric')

#' @export
`julian.R7` <- dottr_s3_dispatcher('julian')

#' @export
`kappa.R7` <- dottr_s3_dispatcher('kappa')

#' @export
`labels.R7` <- dottr_s3_dispatcher('labels')

#' @export
`length.R7` <- dottr_s3_dispatcher('length')

#' @export
`length<-.R7` <- dottr_s3_dispatcher('length<-')

#' @export
`levels.R7` <- dottr_s3_dispatcher('levels')

#' @export
`levels<-.R7` <- dottr_s3_dispatcher('levels<-')

#' @export
`mean.R7` <- dottr_s3_dispatcher('mean')

#' @export
`merge.R7` <- dottr_s3_dispatcher('merge')

#' @export
`months.R7` <- dottr_s3_dispatcher('months')

#' @export
`names.R7` <- dottr_s3_dispatcher('names')

#' @export
`names<-.R7` <- dottr_s3_dispatcher('names<-')

#' @export
`open.R7` <- dottr_s3_dispatcher('open')

#' @export
`pretty.R7` <- dottr_s3_dispatcher('pretty')

#' @export
`qr.R7` <- dottr_s3_dispatcher('qr')

#' @export
`quarters.R7` <- dottr_s3_dispatcher('quarters')

#' @export
`range.R7` <- dottr_s3_dispatcher('range')

#' @export
`rbind.R7` <- dottr_s3_dispatcher('rbind')

#' @export
`rep.R7` <- dottr_s3_dispatcher('rep')

#' @export
`rev.R7` <- dottr_s3_dispatcher('rev')

#' @export
`round.R7` <- dottr_s3_dispatcher('round')

#' @export
`row.names.R7` <- dottr_s3_dispatcher('row.names')

#' @export
`row.names<-.R7` <- dottr_s3_dispatcher('row.names<-')

#' @export
`rowsum.R7` <- dottr_s3_dispatcher('rowsum')

#' @export
`scale.R7` <- dottr_s3_dispatcher('scale')

#' @export
`seek.R7` <- dottr_s3_dispatcher('seek')

#' @export
`seq.R7` <- dottr_s3_dispatcher('seq')

#' @export
`sequence.R7` <- dottr_s3_dispatcher('sequence')

#' @export
`solve.R7` <- dottr_s3_dispatcher('solve')

#' @export
`sort.R7` <- dottr_s3_dispatcher('sort')

#' @export
`split.R7` <- dottr_s3_dispatcher('split')

#' @export
`split<-.R7` <- dottr_s3_dispatcher('split<-')

#' @export
`subset.R7` <- dottr_s3_dispatcher('subset')

#' @export
`summary.R7` <- dottr_s3_dispatcher('summary')

#' @export
`t.R7` <- dottr_s3_dispatcher('t')

#' @export
`toString.R7` <- dottr_s3_dispatcher('toString')

#' @export
`transform.R7` <- dottr_s3_dispatcher('transform')

#' @export
`trunc.R7` <- dottr_s3_dispatcher('trunc')

#' @export
`truncate.R7` <- dottr_s3_dispatcher('truncate')

#' @export
`unique.R7` <- dottr_s3_dispatcher('unique')

#' @export
`units.R7` <- dottr_s3_dispatcher('units')

#' @export
`units<-.R7` <- dottr_s3_dispatcher('units<-')

#' @export
`weekdays.R7` <- dottr_s3_dispatcher('weekdays')

#' @export
`with.R7` <- dottr_s3_dispatcher('with')

#' @export
`within.R7` <- dottr_s3_dispatcher('within')

#' @export
`xtfrm.R7` <- dottr_s3_dispatcher('xtfrm')
